checker:
  display_mode: bolt
  import_from_file: true
  print_fail: false
  print_ms_hit: false
  proxy:
    api_link: null
    proxy: false
    proxy_api: false
    proxy_type: http
  retries: 3
  save_bad: false
  threads: 250
  timeout: 10000000
  webhook:
    Webhook: false
    WebhookID: https://discordapp.com/api/webhooks/
